### ISSUE TITLE
Cannot upgrade version of mermaid for diagrams

### ISSUE THREAD

**Issue by ericis** [ourchitecture/hello-cloud#82]
See: https://github.com/mermaid-js/mermaid/issues/2525

Upgrade to latest and test work-around CSS:

```css
.messageText {
    dominant-baseline: middle;
}
```
